######################################################################
# Automatically generated by qmake (3.0) Fri Mar 6 20:30:14 2015
######################################################################

TEMPLATE = app
TARGET = grammar-flashcards
INCLUDEPATH += .
QT += core gui
QT += widgets

# Input
HEADERS += GrammarFlashcardDialog.h
SOURCES += GrammarFlashcardDialog.cpp main.cpp
