#############################################################################
# Makefile for building: grammar-flashcards.app/Contents/MacOS/grammar-flashcards
# Generated by qmake (3.0) (Qt 5.0.2) on: Fri Mar 6 20:30:56 2015
# Project:  grammar-flashcards.pro
# Template: app
# Command: /Volumes/INTENSO/qt/5.0.2/clang_64/bin/qmake -o Makefile grammar-flashcards.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -mmacosx-version-min=10.6 -O2 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -mmacosx-version-min=10.6 -O2 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/macx-clang -I. -I. -I/Volumes/INTENSO/qt/5.0.2/clang_64/include -I/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets -I/Volumes/INTENSO/qt/5.0.2/clang_64/lib/QtWidgets.framework/Headers -I/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui -I/Volumes/INTENSO/qt/5.0.2/clang_64/lib/QtGui.framework/Headers -I/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore -I/Volumes/INTENSO/qt/5.0.2/clang_64/lib/QtCore.framework/Headers -I. -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Volumes/INTENSO/qt//5.0.2/clang_64/lib -framework QtWidgets -F/Volumes/INTENSO/qt//5.0.2/clang_64/qtbase/lib -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Volumes/INTENSO/qt/5.0.2/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = GrammarFlashcardDialog.cpp \
		main.cpp moc_GrammarFlashcardDialog.cpp
OBJECTS       = GrammarFlashcardDialog.o \
		main.o \
		moc_GrammarFlashcardDialog.o
DIST          = /Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/spec_pre.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/qdevice.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/device_config.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/shell-unix.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/unix.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/mac.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/gcc-base.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/gcc-base-macx.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/clang.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/clang-mac.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/mac-minimum-version.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/qconfig.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_v8.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/qt_functions.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/qt_config.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/macx-clang/qmake.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/spec_post.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/exclusive_builds.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/default_pre.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/unix/default_pre.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/default_pre.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/resolve_config.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/default_post.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/default_post.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/objective_c.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/warn_on.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/qt.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/resources.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/moc.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/unix/opengl.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/uic.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/unix/thread.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/rez.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/sdk.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/testcase_targets.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/exceptions.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/yacc.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/lex.prf \
		grammar-flashcards.pro \
		grammar-flashcards.pro
QMAKE_TARGET  = grammar-flashcards
DESTDIR       = 
TARGET        = grammar-flashcards.app/Contents/MacOS/grammar-flashcards

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-mmacosx-version-min=10.6 \
		-O2 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile grammar-flashcards.app/Contents/PkgInfo grammar-flashcards.app/Contents/Resources/empty.lproj grammar-flashcards.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d grammar-flashcards.app/Contents/MacOS/ || mkdir -p grammar-flashcards.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: grammar-flashcards.pro /Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/macx-clang/qmake.conf /Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/spec_pre.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/qdevice.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/device_config.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/shell-unix.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/unix.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/mac.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/gcc-base.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/gcc-base-macx.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/clang.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/clang-mac.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/mac-minimum-version.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/qconfig.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_v8.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/qt_functions.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/qt_config.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/macx-clang/qmake.conf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/spec_post.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/exclusive_builds.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/default_pre.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/unix/default_pre.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/default_pre.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/resolve_config.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/default_post.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/default_post.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/objective_c.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/warn_on.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/qt.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/resources.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/moc.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/unix/opengl.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/uic.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/unix/thread.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/rez.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/sdk.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/testcase_targets.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/exceptions.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/yacc.prf \
		/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/lex.prf \
		grammar-flashcards.pro \
		/Volumes/INTENSO/qt/5.0.2/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Volumes/INTENSO/qt/5.0.2/clang_64/lib/QtGui.framework/QtGui.prl \
		/Volumes/INTENSO/qt/5.0.2/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile grammar-flashcards.pro
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/spec_pre.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/qdevice.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/device_config.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/shell-unix.conf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/unix.conf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/mac.conf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/gcc-base.conf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/gcc-base-macx.conf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/clang.conf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/clang-mac.conf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/common/mac-minimum-version.conf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/qconfig.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_bootstrap.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_clucene.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_core.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_help.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_network.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_script.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_v8.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/qt_functions.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/qt_config.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/macx-clang/qmake.conf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/spec_post.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/exclusive_builds.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/default_pre.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/unix/default_pre.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/default_pre.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/resolve_config.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/default_post.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/default_post.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/objective_c.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/warn_on.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/qt.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/resources.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/moc.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/unix/opengl.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/uic.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/unix/thread.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/rez.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/mac/sdk.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/testcase_targets.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/exceptions.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/yacc.prf:
/Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/features/lex.prf:
grammar-flashcards.pro:
/Volumes/INTENSO/qt/5.0.2/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Volumes/INTENSO/qt/5.0.2/clang_64/lib/QtGui.framework/QtGui.prl:
/Volumes/INTENSO/qt/5.0.2/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile grammar-flashcards.pro

qmake_all: FORCE

grammar-flashcards.app/Contents/PkgInfo: 
	@test -d grammar-flashcards.app/Contents || mkdir -p grammar-flashcards.app/Contents
	@$(DEL_FILE) grammar-flashcards.app/Contents/PkgInfo
	@echo "APPL????" >grammar-flashcards.app/Contents/PkgInfo
grammar-flashcards.app/Contents/Resources/empty.lproj: 
	@test -d grammar-flashcards.app/Contents/Resources || mkdir -p grammar-flashcards.app/Contents/Resources
	@touch grammar-flashcards.app/Contents/Resources/empty.lproj
	
grammar-flashcards.app/Contents/Info.plist: 
	@test -d grammar-flashcards.app/Contents || mkdir -p grammar-flashcards.app/Contents
	@$(DEL_FILE) grammar-flashcards.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,grammar-flashcards,g" -e "s,@TYPEINFO@,????,g" /Volumes/INTENSO/qt/5.0.2/clang_64/mkspecs/macx-clang/Info.plist.app >grammar-flashcards.app/Contents/Info.plist
dist: 
	@test -d .tmp/grammar-flashcards1.0.0 || mkdir -p .tmp/grammar-flashcards1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/grammar-flashcards1.0.0/ && $(COPY_FILE) --parents GrammarFlashcardDialog.h .tmp/grammar-flashcards1.0.0/ && $(COPY_FILE) --parents GrammarFlashcardDialog.cpp main.cpp .tmp/grammar-flashcards1.0.0/ && (cd `dirname .tmp/grammar-flashcards1.0.0` && $(TAR) grammar-flashcards1.0.0.tar grammar-flashcards1.0.0 && $(COMPRESS) grammar-flashcards1.0.0.tar) && $(MOVE) `dirname .tmp/grammar-flashcards1.0.0`/grammar-flashcards1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/grammar-flashcards1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r grammar-flashcards.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_GrammarFlashcardDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GrammarFlashcardDialog.cpp
moc_GrammarFlashcardDialog.cpp: /Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/QDialog \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/qdialog.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/qwidget.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qwindowdefs.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qglobal.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qconfig.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qfeatures.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsystemdetection.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qcompilerdetection.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qprocessordetection.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qlogging.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qflags.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qtypeinfo.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qtypetraits.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsysinfo.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qobjectdefs.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qnamespace.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qwindowdefs_win.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qobject.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qstring.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qchar.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qbytearray.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qrefcount.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qbasicatomic.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qgenericatomic.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_msvc.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_integrity.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qoldbasicatomic.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_vxworks.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_power.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_alpha.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_armv7.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_armv6.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_armv5.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_bfin.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_ia64.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_mips.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_s390.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_sh4a.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_sparc.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_x86.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_cxx11.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_gcc.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_unix.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qarraydata.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qstringbuilder.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qlist.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qalgorithms.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qiterator.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qcoreevent.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qscopedpointer.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qmetatype.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qvarlengtharray.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qcontainerfwd.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qisenum.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qobject_impl.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qmargins.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpaintdevice.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qrect.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsize.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qpoint.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpalette.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qcolor.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qrgb.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qstringlist.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qdatastream.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qiodevice.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qpair.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qregexp.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qstringmatcher.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qbrush.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qvector.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qmatrix.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpolygon.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qregion.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qline.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qtransform.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpainterpath.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qimage.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpixmap.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsharedpointer.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qshareddata.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsharedpointer_impl.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qhash.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qfont.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qfontmetrics.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qfontinfo.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/qsizepolicy.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qcursor.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qkeysequence.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qevent.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qvariant.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qmap.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qdebug.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qtextstream.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qlocale.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qset.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qcontiguouscache.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qurl.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qurlquery.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qfile.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qfiledevice.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qvector2d.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qtouchdevice.h \
		GrammarFlashcardDialog.h
	/Volumes/INTENSO/qt//5.0.2/clang_64/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__=4 GrammarFlashcardDialog.h -o moc_GrammarFlashcardDialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

GrammarFlashcardDialog.o: GrammarFlashcardDialog.cpp GrammarFlashcardDialog.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/QDialog \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/qdialog.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/qwidget.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qwindowdefs.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qglobal.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qconfig.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qfeatures.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsystemdetection.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qcompilerdetection.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qprocessordetection.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qlogging.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qflags.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qtypeinfo.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qtypetraits.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsysinfo.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qobjectdefs.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qnamespace.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qwindowdefs_win.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qobject.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qstring.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qchar.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qbytearray.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qrefcount.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qbasicatomic.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qgenericatomic.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_msvc.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_integrity.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qoldbasicatomic.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_vxworks.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_power.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_alpha.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_armv7.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_armv6.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_armv5.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_bfin.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_ia64.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_mips.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_s390.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_sh4a.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_sparc.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_x86.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_cxx11.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_gcc.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_unix.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qarraydata.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qstringbuilder.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qlist.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qalgorithms.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qiterator.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qcoreevent.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qscopedpointer.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qmetatype.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qvarlengtharray.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qcontainerfwd.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qisenum.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qobject_impl.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qmargins.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpaintdevice.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qrect.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsize.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qpoint.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpalette.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qcolor.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qrgb.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qstringlist.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qdatastream.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qiodevice.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qpair.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qregexp.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qstringmatcher.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qbrush.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qvector.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qmatrix.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpolygon.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qregion.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qline.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qtransform.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpainterpath.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qimage.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpixmap.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsharedpointer.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qshareddata.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsharedpointer_impl.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qhash.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qfont.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qfontmetrics.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qfontinfo.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/qsizepolicy.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qcursor.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qkeysequence.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qevent.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qvariant.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qmap.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qdebug.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qtextstream.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qlocale.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qset.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qcontiguouscache.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qurl.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qurlquery.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qfile.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qfiledevice.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qvector2d.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qtouchdevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GrammarFlashcardDialog.o GrammarFlashcardDialog.cpp

main.o: main.cpp /Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/QApplication \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/qapplication.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qcoreapplication.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qobject.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qobjectdefs.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qnamespace.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qglobal.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qconfig.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qfeatures.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsystemdetection.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qcompilerdetection.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qprocessordetection.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qlogging.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qflags.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qtypeinfo.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qtypetraits.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsysinfo.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qstring.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qchar.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qbytearray.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qrefcount.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qbasicatomic.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qgenericatomic.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_msvc.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_integrity.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qoldbasicatomic.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_vxworks.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_power.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_alpha.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_armv7.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_armv6.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_armv5.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_bfin.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_ia64.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_mips.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_s390.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_sh4a.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_sparc.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_x86.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_cxx11.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_gcc.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qatomic_unix.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qarraydata.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qstringbuilder.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qlist.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qalgorithms.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qiterator.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qcoreevent.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qscopedpointer.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qmetatype.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qvarlengtharray.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qcontainerfwd.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qisenum.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qobject_impl.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qeventloop.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qwindowdefs.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qwindowdefs_win.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qpoint.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsize.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qcursor.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/qdesktopwidget.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/qwidget.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qmargins.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpaintdevice.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qrect.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpalette.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qcolor.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qrgb.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qstringlist.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qdatastream.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qiodevice.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qpair.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qregexp.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qstringmatcher.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qbrush.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qvector.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qmatrix.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpolygon.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qregion.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qline.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qtransform.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpainterpath.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qimage.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qpixmap.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsharedpointer.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qshareddata.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qsharedpointer_impl.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qhash.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qfont.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qfontmetrics.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qfontinfo.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/qsizepolicy.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qkeysequence.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qevent.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qvariant.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qmap.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qdebug.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qtextstream.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qlocale.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qset.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qcontiguouscache.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qurl.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qurlquery.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qfile.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtCore/qfiledevice.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qvector2d.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qtouchdevice.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qguiapplication.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtGui/qinputmethod.h \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/QDialog \
		/Volumes/INTENSO/qt/5.0.2/clang_64/include/QtWidgets/qdialog.h \
		GrammarFlashcardDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_GrammarFlashcardDialog.o: moc_GrammarFlashcardDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GrammarFlashcardDialog.o moc_GrammarFlashcardDialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

